#
# Copyright (c) 2019 Cigna Corporation. All Rights Reserved.
# This software is the confidential and proprietary information of  Cigna Corporation. ("Confidential Information").
#  You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the agreement you entered into with Cigna Corporation.
#
#
#

sonar.projectKey=enterprise-pipeline-framework
sonar.projectName=enterprise-pipeline-framework
sonar.projectVersion=1.0.0
sonar.sources=src,vars
sonar.tests=test
sonar.java.binaries=target/
sonar.kubernetes.activate=true
