package com.evernorth.cloudnativebuild.config

class ReleaseConstants {

    /**
     * The name of the default release module
     */
    public static final String RELEASE_MODULE_NAME = "cnp-release-xlr"
    public static final String RELEASE_DEFAULT_STASH_PATTERN = "*manifest.y*l,release.info,package.json,pom.xml,Dockerfile,deployment*/**/**"
    public static final String ReleaseStashName = "releaseStash"

    /**
     * Name of the zipfile such as deploymentPackage_1.1.1.zip. This is always generated from pipeline, not passed in
     * by Jenkinsfile
     */
    public static final String DEPLOYMENT_PACKAGE_PROPERTY_NAME = "deploymentPackage"

    /**
     * Property that contains Full path to deployment package in package repo. This property can be passed in Jenkinsfile
     * or derived from build step in pipeline. In Jenkins you can pass StepResult to next or have pipeline do it automatically
     * if only one build module included.
     */
    public static final String DEPLOYMENT_PACKAGE_PATH_PROPERTY_NAME = "deploymentPackagePath"

    /**
     * Normally generated by pipeline, but can be overridden in Jenkinsfile or by modifying values in XLR
     */
    public static final String ROLLBACK_PACKAGE_PATH_PROPERTY_NAME = "rollbackDeploymentPackagePath"

    /**
     * Property name of artifact from output of build / publish module
     */
    public static final String PUBLISH_URL_PROPERTY_NAME ="publishUrl"

    /**
     * Property Name for artifact when included in Deploy or Cutover module
     */
    public static final String ARTIFACT_PROPERTY_NAME = "artifact"

    /**
     * URL to Git Repo that contains the project source code
     */
    public static final String REPO_URL_PROPERTY_NAME = "repoUrl"

    /**
     * The name of the current branch
     */
    public static final String BRANCH_NAME_PROPERTY_NAME = "branchName"

    /**
     * Generated by build module and passed to pipeline in output argument
     */
    public static final String ARTIFACT_VERSION_PROPERTY_NAME="artifactVersion"

    /**
     * Artifactory repo where deployment files are stored during release finalize
     */
    public static final String ARTIFACTORY_DEPLOY_RELEASE_REPO = 'ci-release-local'

    /**
    * Artifactory repo where deployment files are stored during deployment
    */
    public static final String ARTIFACTORY_DEPLOY_SNAPSHOT_REPO = 'ci-snapshot-local'

    /**
     * Artifactory repo where deployment files are stored during release finalize
     */
    public static final String ARTIFACTORY_ARTIFACT_RELEASE_REPO = 'libs-release-local'

    /**
     * Artifactory repo where deployment files are stored during deployment
     */
    public static final String ARTIFACTORY_ARTIFACT_SNAPSHOT_REPO = 'libs-snapshot-local'

    /**
     * Property name of the Release ID sent from release module
     */
    public static final String RELEASE_ID_PROPERTY_NAME = "xlrReleaseID"

    /**
     * rollback subcommand
     */
    public static final String ROLLBACK_SUBCOMMAND = "rollback"

    /**
     * Key for pipelineLibraryName added to release arguments
     */
    public static final String PIPELINE_LIBRARY_PARAMETER_NAME = "pipelineLibraryName"

}
