package com.evernorth.cloudnativebuild.model

import com.cloudbees.groovy.cps.NonCPS
import com.evernorth.cloudnativebuild.data.PipelineConstants
import com.evernorth.cloudnativebuild.data.PipelineEventType

/**
 * Defines the module contract between EPF and cnp that allows conduit to manage stashing, etc
 * as defined for CNP modules.
 */
class ModuleContract implements Serializable, Cloneable {
    /**
     * The name of the plugin contract
     */
    String contractName = ''

    /**
     * CommandName - The name of the command or service endpoint. It is expected that
     * the command will be in the system path and that group 0 and Jenkins user will
     * have execute permission on the image
     */
    String commandName = ''

    /**
     * The name of the module such as cnp-build-go. If this value is not provided then it will use the
     * commandName property excluding content after first dot. For example if commandName is
     * cnp-package-deb.sh then moduleName will be cnp-package-deb
     */
    String moduleName = ''

    /**
     * subCommand - This is an optional parameter that can be used when multiple plugins have been combined
     * into single command line utility
     */
    String subCommand = ''

    /**
     * If the command has a preflight check command, enter the command name and it will be registered
     * automatically as new preflight check module
     */
    String preflightSubCommand = ''

    /***
     * When command is written a language such as python or Java you will need to add a prefix that will be
     * added to the shell command. For example to execute a Java commandline tool you would use
     * "java -jar " as your command prefix
     */
    String commandPrefix = ''

    /***
     * If your module needs to use a credential defined on the Jenkins Master then you need to enter
     * a value or list of values in this property.
     */
    Credential[] credentials

    /**
     * The tag for the image that will be used for this part of the build. Typically it will include the URL
     * to the image repository followed by an image name and a version for example:
     * devops/defaultCbcExecutor:1.0.1
     *
     * Note this property is normally overwritten by property set from Jenkins file.
     */
    String image = ''

    /***
     * The stage of the pipeline lifecycle where the module should be fired
     */
    String buildStage = ''

    /**
     * The directory where output generated by the step will be placed
     */
    String outputDirectory = ''

    /**
     * If the module uses a logfile to send results back to Jenkins, you can enter a name here.
     * If this is omitted and useLogFile is true then the log file name will be generated from
     * moduleName property.
     */
    String logFileName

    @NonCPS
    String getLogFileName() {
        if (!logFileName)
            logFileName = "$moduleName${PipelineConstants.LOG_FILE_POSTFIX}"

        logFileName
    }
    /**
     * If true then the ExecuteShellModuleStep will attempt to generate the StepResult using contents of
     * a logfile with the name specified in the logFileName property in the root of the workspace
     */
    boolean useLogFile = false

    /**
     * If the Module requires saving files that can be used by other steps, you must set the requiresStash to true
     */
    boolean requiresStash = false

    /**
     * If the Module requires using files created in another step, you must set the requiresUnStash to true
     */
    boolean requiresUnStash = false

    /**
     * if true, scm remote url will be passed as arg to module
     */
    boolean allowPipelineToModifyArgumentList = false

    /**
     * If your module only needs to stash or unstash a specific set of files that are not defined in one of
     * the stash patterns defined in PipelineConstants, you can define it here.
     * If you use this property you also need to define a stashName
     */
    String stashPattern = ''

    // TODO need to find a generic option for all build types, this is specifically for npm builds
    /**
     * If your module only needs to exclude set of files fron stashing that are not defined in one of
     * the stash patterns defined in PipelineConstants, you can define it here.
     * If you use this property you also need to define a stashName
     */
    String excludesPattern = ''

    /**
     * If you are using a custom stash pattern you must set a stashName
     */
    String stashName = ''

    /**
     * Flags module as requiring full source and will perform a checkout prior to the start of execution
     */
    boolean requireCheckout = false

    /**
     * If you need to unStash, what is the name of the stash
     */
    String unStashName = ''

    /**
     * If you are using repeated tasks, this will help identify the step, if this is not defined,
     * the contract type will be used
     */
    String stageName = ''

    boolean allowNonStandardDeployment = false

    /**
     * Allows a module to emit a pre-execution event. This would cause event driven modules
     * that listened for the PipelineEventType listed to execute before the Module is executed.
     */
    PipelineEventType preExecuteEvent = null

    /**
     * Allows a module to emit a post-execution event. This would allow event driven modules that listen for the
     * PipelineEventType listed to execute after the Module is executed
     */
    PipelineEventType postExecuteEvent = null

    /**
     * List of PipelineEventTypes that this module listens for. Modules that have a value
     * attached to this property should not be used with Jenkinsfile verbs
     * but are instead triggered when a module that emits an Event is executed
     */
    List<PipelineEventType> triggeredByEvent = []

    /**
     * Glob expression for files in repo to be included in deployment package
     */
    String releasePackageFileInclusionPattern = ''

    /**
     * The type of artifact generated for the application, values include
     * archive (can be zip, jar, tgz, deb, rpm, etc)
     * container (image stored in artifactory or quay)
     * gittag (for scripts that need not be built, eg, terraform)
     */
    String artifactType = PipelineConstants.ARTIFACT_TYPE_ARCHIVE

    /**
     * The requested resources for this contract. Any provided values override the defaults in DEFAULT_REQUESTS.
     */
    Map<String, Integer> requests = [:]

    /**
     * The resource limits for this contract.
     */
    Map<String, Integer> limits = [:]


    @Override
    @NonCPS
    int hashCode() {
        int result
        result = ( contractName != null ? contractName.hashCode() : 0 )
        result = 31 * result + ( commandName != null ? commandName.hashCode() : 0 )
        result = 31 * result + ( subCommand != null ? subCommand.hashCode() : 0 )
        result = 31 * result + ( commandPrefix != null ? commandPrefix.hashCode() : 0 )
        result = 31 * result + ( moduleName != null ? moduleName.hashCode() : 0 )
        return result
    }

    @Override
    @NonCPS
    String toString() {
        'ModuleContract{' +
            "contractName='" + contractName + '\'' +
            ", commandName='" + commandName + '\'' +
            ", moduleName='" + moduleName + '\'' +
            ", subCommand='" + subCommand + '\'' +
            ", commandPrefix='" + commandPrefix + '\'' +
            ", credentials=" + Arrays.toString(credentials.findAll { it != null }) +
            ", request=" + requests +
            ", limits=" + limits +
            ", image='" + image + '\'' +
            ", buildStage='" + buildStage + '\'' +
            ", outputDirectory='" + outputDirectory + '\'' +
            ", logFileName='" + logFileName + '\'' +
            ", useLogFile=" + useLogFile +
            ", requiresStash=" + requiresStash +
            ", requireCheckout=" + requireCheckout +
            ", requiresUnStash=" + requiresUnStash +
            ", allowPipelineToModifyArgumentList=" + allowPipelineToModifyArgumentList +
            ", stashPattern='" + stashPattern + '\'' +
            ", stashName='" + stashName + '\'' +
            ", unStashName='" + unStashName + '\'' +
            ", stageName='" + stageName + '\'' +
            ", allowNonStandardDeployment=" + allowNonStandardDeployment +
            ", triggeredByEvent=" + triggeredByEvent +
            ", releasePackageFileInclusionPattern='" + releasePackageFileInclusionPattern + '\'' +
            ", artifactType='" + artifactType + '\'' +
            '}'
    }
}
